import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from '@/core/providers/react-query-provider'
import { ThemeProvider } from '@/core/components/ui/context/theme-context'
import { Toaster } from '@pheralb/toast'
import { Space_Grotesk } from 'next/font/google'
const spaceGrotesk = Space_Grotesk({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        <ReactQueryProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </ReactQueryProvider>
        <Toaster position='top-center' toastOptions={{
          font: "inherit"
        }}/>
        <div id='react-modals'/>
      </body>
    </html>
  );
}
